msi: Refactor to allow custom packages
* configure.ac: New package "gnupg-msi" to allow version independet
  packaging.
* m4/gpg4win.m4 (GPG4WIN_BPKG_MSISRC): New macro for including
wixlibs.
* po/gpg4win-de.wxl, po/gpg4win-en.wxl: New strings.
* src/Makefile.am (stamps/stamp-msi-base): New.
* playground/install/gpg4win-$(VERSION).wixlib,
gpg4win-$(VERSION).wxs: Moved around and modified.
* src/WixUI_Gpg4win: Start some layout experiments.
* src/gpg4win.mk.in (SETVARS_WINE, SETVARS_WINE_TWO_DOLLAR)
(MSI_template): New templates to generate MSI targets.
* stamps/stamp-versions-all-signed: Target to sign
VERSION files.
* src/make-msi.pl: Generate wxs files for customized
configuration.

--
This enables the Gpg4win repo to create custom MSI packages
that contain a specific configuration, trusted root ca's etc.
and which might even contain a different GnuPG version as
we plan to branch between Gpg4win that contains GnuPG 2.3
and GnuPG Desktop which due to delays in evaluation etc. will
be more conservative and contain the GnuPG stable 2.2 branch.

diff --git a/src/gpg4win.mk.in b/src/gpg4win.mk.in
--- a/src/gpg4win.mk.in
+++ b/src/gpg4win.mk.in
@@ -110,6 +110,91 @@ define SETVARS_EX
 	export SYSROOT="$(ex_idir)"
 endef
 
+define SETVARS_WINE
+	set -e; \
+	if [ -z "$$$$(which $(WINE))" ]; then \
+		echo "ERROR: For the msi-package wine needs to be installed."; \
+	exit 1; \
+	fi; \
+	if [ -z "$(WIXPREFIX)" ]; then \
+		if [ -d `readlink -f ~/w32root/wixtools` ]; then \
+			WIXPREFIX2=`readlink -f ~/w32root/wixtools`; \
+			echo "Using $$$$WIXPREFIX2 as WIXPREFIX"; \
+		else \
+			echo "ERROR: You must set WIXPREFIX to an installation of wixtools."; \
+			exit 1; \
+		fi; \
+	else \
+		WIXPREFIX2="$(WIXPREFIX)"; \
+	fi; \
+	if [ -z "$$$$WINEPREFIX" ]; then \
+		WINEPREFIX="$$$$HOME/.wine"; \
+		if [ ! -e "$$$$WINEPREFIX/dosdevices" ]; then \
+			echo "ERROR: No wine prefix found under $$WINEPREFIX"; \
+			exit 1; \
+		fi; \
+	fi; \
+	WINEINST=$$$$WINEPREFIX/dosdevices/k:; \
+	WINESRC=$$$$WINEPREFIX/dosdevices/i:; \
+	WINEINSTEX=$$$$WINEPREFIX/dosdevices/j:; \
+	if [ -e "$$$$WINEINST" ]; then \
+		echo "ERROR: $$$$WINEINST already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	if [ -e "$$$$WINESRC" ]; then \
+		echo "ERROR: $$$$WINESRC already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	if [ -e "$$$$WINEINSTEX" ]; then \
+		echo "ERROR: $$$$WINEINSTEX already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	MSI_VERSION=$$$$(echo $(VERSION) | tr -s \\-beta .)
+endef
+
+# Same as above
+define SETVARS_WINE_TWO_DOLLAR
+	set -e; \
+	if [ -z "$$(which $(WINE))" ]; then \
+		echo "ERROR: For the msi-package wine needs to be installed."; \
+	exit 1; \
+	fi; \
+	if [ -z "$(WIXPREFIX)" ]; then \
+		if [ -d `readlink -f ~/w32root/wixtools` ]; then \
+			WIXPREFIX2=`readlink -f ~/w32root/wixtools`; \
+			echo "Using $$WIXPREFIX2 as WIXPREFIX"; \
+		else \
+			echo "ERROR: You must set WIXPREFIX to an installation of wixtools."; \
+			exit 1; \
+		fi; \
+	else \
+		WIXPREFIX2="$(WIXPREFIX)"; \
+	fi; \
+	if [ -z "$$WINEPREFIX" ]; then \
+		WINEPREFIX="$$HOME/.wine"; \
+		if [ ! -e "$$WINEPREFIX/dosdevices" ]; then \
+			echo "ERROR: No wine prefix found under $$WINEPREFIX"; \
+			exit 1; \
+		fi; \
+	fi; \
+	WINEINST=$$WINEPREFIX/dosdevices/k:; \
+	WINESRC=$$WINEPREFIX/dosdevices/i:; \
+	WINEINSTEX=$$WINEPREFIX/dosdevices/j:; \
+	if [ -e "$$WINEINST" ]; then \
+		echo "ERROR: $$WINEINST already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	if [ -e "$$WINESRC" ]; then \
+		echo "ERROR: $$WINESRC already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	if [ -e "$$WINEINSTEX" ]; then \
+		echo "ERROR: $$WINEINSTEX already exists. Please remove."; \
+		exit 1; \
+	fi; \
+	MSI_VERSION=$$(echo $(VERSION) | tr -s \\-beta .)
+endef
+
 # Support macro.  Unpack the archive $(1).
 define DEFLATE_macro
 	rm -rf $$$${pkgsdir}; \
@@ -707,7 +792,73 @@ $(if $(filter-out no, $(call GETVAR,gpg4win_pkg_$(1))),
   $(call KDEPKG_template_,$1))
 endef
 
+define MSI_template
 
+.PHONY : $(1)-package
+$(1)-package: installers/GnuPG-VS-Desktop-$(VERSION)-$(1).msi
+
+playground/install/$(1).wixlib: gnupg-vsd/$(1)/$(1).wxs
+	($(call SETVARS_WINE,); \
+	( \
+	ln -s $(idir) $$$$WINEINST; \
+	ln -s $(ex_idir) $$$$WINEINSTEX; \
+	ln -s `readlink -f $(top_srcdir)` $$$$WINESRC; \
+		$(WINE) $$$$WIXPREFIX2/candle.exe \
+		-dInstDir=k: \
+		-dInstDirEx=j: \
+		-dSrcDir=i:\\src \
+		-dVersion=$$$$MSI_VERSION \
+		-out k:\\$(1)-$(VERSION).wixobj \
+		-pedantic -wx i:\\src\\gnupg-vsd\\$(1)\\$(1).wxs || exit 1;\
+		$(WINE) $$$$WIXPREFIX2/lit.exe \
+		-out k:\\$(1).wixlib \
+		-bf \
+		-wx \
+		-pedantic \
+		k:\\$(1)-$(VERSION).wixobj || exit 1; \
+		\
+	) || ERR=1; \
+		(rm $$$$WINEINST; rm $$$$WINESRC; rm $$$$WINEINSTEX); \
+	if [ -n "$$$$ERR" ]; then \
+		exit 1; \
+	fi \
+	)
+
+# This is generated by make-msi.pl
+gnupg-vsd/$(1)/$(1).wxs: gnupg-vsd/$(1)/VERSION.sig make-msi.pl gpg4win-$(VERSION).wxs
+
+gnupg-vsd/$(1)/VERSION.sig: gnupg-vsd/$(1)/VERSION
+	echo "----------SIGNING----------"
+	echo "using key: $(msi_signkey)"
+	cat gnupg-vsd/$(1)/VERSION
+	gpg --yes -o gnupg-vsd/$(1)/VERSION.sig -bau $(msi_signkey) gnupg-vsd/$(1)/VERSION
+
+gnupg-vsd/$(1)/VERSION: gnupg-vsd/custom.mk
+	echo "$(call GETVAR,msi_target_$(1)_VERSION)" > gnupg-vsd/$(1)/VERSION
+
+installers/GnuPG-VS-Desktop-$(VERSION)-$(1).msi: stamps/stamp-msi-base playground/install/$(1).wixlib \
+	gnupg-vsd/$(1)/license.rtf
+	scp gnupg-vsd/$(1)/license.rtf \
+		 $(WINHOST):AppData/Local/Temp/gpg4win-$(VERSION); \
+	scp playground/install/$(1).wixlib \
+		 $(WINHOST):AppData/Local/Temp/gpg4win-$(VERSION); \
+	scp $(call GETVAR,msi_target_$(1)_branding)/*.bmp \
+		 $(WINHOST):AppData/Local/Temp/gpg4win-$(VERSION); \
+	ssh $(WINHOST) "cd AppData/Local/Temp/gpg4win-$(VERSION) && $(WINLIGHT) \
+	-spdb \
+	-ext WixUIExtension \
+	-out GnuPG-Desktop-$(VERSION)-$(1).msi \
+	 $(call GETVAR,msi_target_$(1)_l10n) \
+	-dcl:high \
+	-v -pedantic \
+	 \
+	 gpg4win-$(VERSION).wixlib \
+	 gnupg-msi-$(gpg4win_pkg_gnupg_msi_version)-bin.wixlib \
+	 $(1).wixlib"; \
+	 scp $(WINHOST):AppData/Local/Temp/gpg4win-$(VERSION)/GnuPG-Desktop-$(VERSION)-$(1).msi \
+	 installers;
+
+endef
 
 # Insert the template for each source package.
 $(foreach spkg, $(gpg4win_spkgs), $(eval $(call SPKG_template,$(spkg))))
@@ -733,7 +884,6 @@ $(foreach kdepkg, $(gpg4win_kdepkgs), $(eval $(call KDEPKG_template,$(kdepkg))))
 # Insert the template for qt packages.
 $(foreach qtpkg, $(gpg4win_qtpkgs), $(eval $(call QTPKG_template,$(qtpkg))))
 
-
 $(foreach rll, $(gpg4win_howto_smime_ll), \
                $(eval $(call HOWTO_template,SMIME,$(rll))))
 
@@ -747,7 +897,6 @@ stamps/stamp-final: $(addprefix stamps/stamp-final-,$(gpg4win_build_list)) \
 $(bdir)/versioninfo.txt: stamps/stamp-final
 	touch $(bdir)/versioninfo.txt
 
-
 all-gpg4win: stamps/stamp-final
 
 # Just to check if we catched all stamps.
@@ -757,7 +906,19 @@ clean-stamps:
 clean-gpg4win:
 	$(RM) -fR playground stamps
 
-.PHONY : all-gpg4win clean-stamps clean-gpg4win
+stamps/stamp-versions-all-signed: \
+	$(addsuffix /VERSION.sig, $(addprefix gnupg-vsd/,$(msi_targets))) \
+
+msi: stamps/stamp-versions-all-signed \
+	$(addsuffix .msi,$(addprefix installers/GnuPG-VS-Desktop-$(VERSION)-,$(msi_targets)))
+	if [ -z "$(addsuffix .msi,$(addprefix installers/GnuPG-VS-Desktop-$(VERSION)-,$(msi_targets)))" ]; then \
+		echo "No MSI targets configured."; \
+	fi
+
+.PHONY : all-gpg4win clean-stamps clean-gpg4win msi
+
+# Insert the template for msi packages.
+$(foreach msipkg, $(msi_targets), $(eval $(call MSI_template,$(msipkg))))
 
 # @emacs_local_vars_begin@
 # @emacs_local_vars_read_only@
