2008-08-01  Marcus Brinkmann  <marcus@g10code.de>
	* src/pkg-config: Return exit code of pkg-config.

diff --git a/src/pkg-config b/src/pkg-config
--- a/src/pkg-config
+++ b/src/pkg-config
@@ -43,8 +43,9 @@ then
 #    echo "PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR" >&2
 #    echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >&2
 #    echo "OKAY" >&2;
-    exit 0;
+    # See question 11 in comp.unix.shell FAQ.
+    exit ${PIPESTATUS[0]};
 else
-    echo "pkg-config failed!" >&2 
+    echo "pkg-config pipe failed!" >&2 
     exit 1
 fi
